### ISSUE TITLE
брати вниманий

### ISSUE THREAD

**Issue by Sanes** [vazhnov/ansible_webserver#1]
Авось сгодится? Поговорить надо. Можешь звонить ночью, я трубку подниму.
https://bitbucket.org/Drobkov/

**Comment by vazhnov** [comment]
Предпочтительно джаббером или электропочтой: vazhnov@yandex.ru.

**Comment by Sanes** [comment]
Pidgin глупит. Можем по скайпу связаться? Skype: adrobkov
